name: Create Environment Flow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment:"
        required: true
        type: choice
        default: "dev"
        options:
          - "dev"
          - "qa"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display chosen environment
        run: |
          echo "The chosen environment is: ${{ github.event.inputs.environment }}"

      - name: Conditional step for Dev environment
        if: ${{ github.event.inputs.environment == 'dev' }}
        run: |
          echo "Performing actions specific to the 'dev' environment..."
          # Add your dev-specific commands here
          echo "Deploying to development server..."

      - name: Conditional step for QA environment
        if: ${{ github.event.inputs.environment == 'qa' }}
        run: |
          echo "Performing actions specific to the 'qa' environment..."
          # Add your qa-specific commands here
          echo "Deploying to QA server..."

      - name: Run common deployment script
        run: |
          echo "Running common deployment script for ${{ github.event.inputs.environment }}..."
          # You can pass the environment to a script like this:
          # ./deploy-script.sh ${{ github.event.inputs.environment }}
