name: Create Environment Flow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment:"
        required: true
        type: choice
        default: "dev"
        options:
          - "dev"
          - "qa"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_environment: ${{ github.event.inputs.environment }}

jobs:
  terraform:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -backend-config="${{ github.event.inputs.environment }}.tfbackend"

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ github.event.inputs.environment }}"

      - name: Terraform Apply
        if: github.event.inputs.environment != 'none'
        run: terraform apply -auto-approve -var="environment=${{ github.event.inputs.environment }}"
