name: Create Environment Flow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment:"
        required: true
        type: choice
        default: "none"
        options:
          - "dev"
          - "qa"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_environment: ${{ github.event.inputs.environment }}

jobs:
  Create-Infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Working Directory
        run: pwd

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 

      - name: Debug - List Folders
        run: ls -R

      - name: Initialize Terraform
        run: |
          pwd
          cd dev
          terraform init -backend-config="${{ github.event.inputs.environment }}.backend.tf"

      - name: Terraform Plan
        run: |
          pwd
          cd dev
          terraform plan -var="environment=${{ github.event.inputs.environment }}"

      - name: Terraform Apply
        run: |
          pwd
          cd dev
          terraform apply -auto-approve -var="environment=${{ github.event.inputs.environment }}"
