name: Deploy Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_environment: ${{ github.event.inputs.environment }}

jobs:
  terraform:
    name: Deploy Terraform Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform  # Path to your Terraform code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init -backend-config="${{ github.event.inputs.environment }}-backend.tfvars"

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ github.event.inputs.environment }}"

      - name: Terraform Apply
        if: github.event.inputs.environment != 'prod' # Only auto-apply for non-prod, protect prod
        run: terraform apply -auto-approve -var="environment=${{ github.event.inputs.environment }}"

      - name: Require Manual Approval for Prod
        if: github.event.inputs.environment == 'prod'
        run: |
          echo "Manual approval required for prod. Run apply manually after review."




      
