name: Create Environment Flow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment:"
        required: true
        type: choice
        default: "dev"
        options:
          - "dev"
          - "qa"

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/.  # Adjust if your .tf files are elsewhere

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Show selected environment
        run: echo "Selected environment: ${{ github.event.inputs.environment }}"

      - name: Terraform Init
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          echo "Running terraform init with backend config: ${ENVIRONMENT}.tfbackend"
          terraform init -backend-config="${ENVIRONMENT}.tfbackend"

      - name: Terraform Plan
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          echo "Running terraform plan for $ENVIRONMENT"
          terraform plan -var="environment=$ENVIRONMENT"

      - name: Terraform Apply
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          echo "Running terraform apply for $ENVIRONMENT"
          terraform apply -auto-approve -var="environment=$ENVIRONMENT"
