name: Create Environment Flow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environments:"
        required: true
        type: choice
        default: "none"
        options:
          - "dev"
          - "qa"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_environment: ${{ github.event.inputs.environments }}

jobs:
  Create-Infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Working Directory
        run: pwd

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 

      - name: Debug - List Folders
        run: ls -R

      - name: change workdir
        run:  cd terraform/environments/${{ github.event.inputs.environments }}

      - name: terraform Init
        run: terraform init -backend-config="${{ github.event.inputs.environments }}.backend.tf"

      - name: Terraform Plan
        run: terraform plan -var="environments=${{ github.event.inputs.environments }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="environments=${{ github.event.inputs.environments }}"
